# Generated by Django 6.1.1 on 2026-09-30 19:03

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("serial", models.CharField(max_length=100, unique=True)),
                (
                    "registration_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("laboratory", "Laboratory"),
                            ("warehouse", "Warehouse"),
                            ("serverRoom", "Server Room"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CommonArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("corridor", "Corridor"),
                            ("lobby", "Lobby"),
                            ("server_room", "Server Room"),
                            ("other", "Other"),
                        ],
                        default="corridor",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Directorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeneralDirectorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccessPoint",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.device",
                    ),
                ),
                ("gps_lat", models.FloatField(blank=True, null=True)),
                ("gps_lon", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("nodes.device",),
        ),
        migrations.CreateModel(
            name="AllInOneComputer",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.device",
                    ),
                ),
                ("cpu", models.CharField(max_length=100)),
                ("ram_gb", models.IntegerField()),
                ("storage_gb", models.IntegerField()),
                ("screen_size", models.CharField(max_length=10)),
                ("pid", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("nodes.device",),
        ),
        migrations.CreateModel(
            name="DesktopComputer",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.device",
                    ),
                ),
                ("cpu", models.CharField(max_length=100)),
                ("ram_gb", models.IntegerField()),
                ("storage_gb", models.IntegerField()),
                ("pid", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("nodes.device",),
        ),
        migrations.CreateModel(
            name="LaptopComputer",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.device",
                    ),
                ),
                ("cpu", models.CharField(max_length=100)),
                ("ram_gb", models.IntegerField()),
                ("storage_gb", models.IntegerField()),
                ("screen_size", models.CharField(max_length=10)),
                ("battery_capacity", models.CharField(max_length=50)),
                ("pid", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("nodes.device",),
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.device",
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        choices=[("analog", "Analog"), ("digital", "Digital")],
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.IntegerField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("nodes.device",),
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.device",
                    ),
                ),
                (
                    "printer_type",
                    models.CharField(
                        choices=[
                            ("laser", "Laser"),
                            ("inkjet", "Inkjet"),
                            ("multifunction", "Multifunction"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("nodes.device",),
        ),
        migrations.CreateModel(
            name="ServerComputer",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.device",
                    ),
                ),
                ("rack_unit", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("nodes.device",),
        ),
        migrations.CreateModel(
            name="Switch",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.device",
                    ),
                ),
                (
                    "layer_capability",
                    models.CharField(
                        choices=[
                            ("L2", "Layer 2"),
                            ("L3", "Layer 3"),
                            ("L2+L3", "Layer 2 + Layer 3"),
                        ],
                        default="L2",
                        max_length=10,
                    ),
                ),
                ("total_ports", models.IntegerField()),
                ("poe_supported", models.BooleanField(default=False)),
                ("poe_budget_watts", models.IntegerField(blank=True, null=True)),
                (
                    "uplink_speed",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "downlink_speed",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("nodes.device",),
        ),
        migrations.CreateModel(
            name="Ups",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.device",
                    ),
                ),
                ("capacity_va", models.IntegerField()),
            ],
            options={
                "verbose_name": "UPS",
                "verbose_name_plural": "UPS units",
            },
            bases=("nodes.device",),
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="buildings",
                        to="nodes.area",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="city_name_ci_unique",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="area",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="areas",
                to="nodes.city",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="common_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Common area where this device is located (for corridors/shared spaces)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="nodes.commonarea",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "directorate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="nodes.directorate",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("floor_number", models.IntegerField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="floors",
                        to="nodes.building",
                    ),
                ),
            ],
            options={
                "ordering": ["floor_number"],
            },
        ),
        migrations.AddField(
            model_name="commonarea",
            name="floor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="common_areas",
                to="nodes.floor",
            ),
        ),
        migrations.AddField(
            model_name="directorate",
            name="general_directorate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="directorates",
                to="nodes.generaldirectorate",
            ),
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offices",
                        to="nodes.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Peripheral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "peripheral_type",
                    models.CharField(
                        choices=[
                            ("keyboard", "Keyboard"),
                            ("monitor", "Monitor"),
                            ("mouse", "Mouse"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("specifications", models.TextField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peripherals",
                        to="nodes.device",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("room_code", models.CharField(max_length=50)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="nodes.floor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Socket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "socket_code",
                    models.CharField(
                        help_text="Unique identifier for the socket.", max_length=50
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sockets",
                        to="nodes.building",
                    ),
                ),
                (
                    "common_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sockets",
                        to="nodes.commonarea",
                    ),
                ),
            ],
            options={
                "ordering": ["socket_code"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="socket",
            field=models.ForeignKey(
                blank=True,
                help_text="Socket this device is plugged into (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="nodes.socket",
            ),
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to="nodes.room",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="socket",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sockets",
                to="nodes.space",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="space",
            field=models.ForeignKey(
                blank=True,
                help_text="Space where this device is located (for regular offices/rooms)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="nodes.space",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="nodes.department",
                    ),
                ),
                (
                    "directorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="nodes.directorate",
                    ),
                ),
                (
                    "general_directorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="users",
                        to="nodes.generaldirectorate",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="nodes.office",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("shared", "Shared"),
                            ("temporary", "Temporary"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="nodes.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nodes.user"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("area"),
                name="building_name_ci_unique_per_area",
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("city"),
                name="area_city_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("directorate", "name"), name="unique_department_per_directorate"
            ),
        ),
        migrations.AddConstraint(
            model_name="floor",
            constraint=models.UniqueConstraint(
                fields=("building", "floor_number"),
                name="unique_floor_number_per_building",
            ),
        ),
        migrations.AddConstraint(
            model_name="floor",
            constraint=models.CheckConstraint(
                condition=models.Q(("floor_number__gte", -2)),
                name="floor_number_min_minus_2",
                violation_error_message="The floor number cannot be less than -2.",
            ),
        ),
        migrations.AddConstraint(
            model_name="commonarea",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("floor"),
                name="commonarea_name_ci_unique_per_floor",
            ),
        ),
        migrations.AddConstraint(
            model_name="directorate",
            constraint=models.UniqueConstraint(
                fields=("general_directorate", "name"), name="unique_directorate_per_gd"
            ),
        ),
        migrations.AddConstraint(
            model_name="office",
            constraint=models.UniqueConstraint(
                fields=("department", "name"), name="unique_office_per_department"
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("room_code"),
                models.F("floor"),
                name="room_code_ci_unique_per_floor",
            ),
        ),
        migrations.AddConstraint(
            model_name="space",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("room"),
                name="unique_space_name_per_room_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="socket",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("socket_code"),
                models.F("building"),
                name="socket_code_ci_unique_per_building",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("socket__isnull", False)),
                fields=("socket",),
                name="unique_socket_per_device",
            ),
        ),
    ]
