# Generated by Django 6.1.1 on 2026-10-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
